### ISSUE TITLE
Bottom paragraph of features/standards is insivible

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#56]
http://openscap-lhorakov.rhcloud.com/features/standards/

I wanted to write the section but noticed that the text is already there, it's just not visible.

**Comment by lhorakov** [comment]
Done

**Comment by mpreisler** [comment]
I still have the issue in Google Chrome 45.0.2454.101 (64-bit).

I have refreshed everything with Shift+F5 and can still reproduce the issue.

**Comment by lhorakov** [comment]
Oh, ok. I solved it. New bootstrap does not respect any changes in grid, as feature "column-count" so I removed it in lower level and now it's working. Don't know why only chrome and safari had these problems...
